### ISSUE TITLE
GA2BQ Importer - Google analytics API error

### ISSUE THREAD

**Issue by bsq-panagiotis** [google/crmint#121] opened 2019-07-17 10:25 UTC
I started getting the following error today when using the GA2BQ importer:
![image](https://user-images.githubusercontent.com/30236897/61367788-0e003980-a895-11e9-9932-98da48d8ef0a.png)

It seems like the domain name of the GA API calls must change from "analytics.googleapis.com" to "analyticsreporting.googleapis.com" (according to [this](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/installed-py#3_setup_the_sample) and [this](https://stackoverflow.com/questions/56980577/google-discovery-api-the-request-is-missing-a-valid-api-key) )

Is anybody else having similar issues?

**Comment by benpowis** [comment] 2019-07-17 11:14
Yes, I am also getting this error over the past couple of days!

**Comment by bsq-panagiotis** [comment] 2019-07-17 12:14
@benpowis Did you manage to find any way to workaround the issue?

**Comment by benpowis** [comment] 2019-07-17 14:15
@bsq-panagiotis No I haven't been able to find the location in the code to update this, can you help @Slony ?

**Comment by dimitris-bsq** [comment] 2019-07-17 15:02
@benpowis

I applied the solution @bsq-panagiotis mentioned and worked. 

The call of _build_ function of analytics api client included on the function "_ga_setup" of GAWorker class on the file  _workers.py_ (line 393)

**Comment by tushspeed** [comment] 2019-07-18 11:18
@dimitris-bsq How did you deploy the changes to app engine/ GCP? thanks!

**Comment by dimitris-bsq** [comment] 2019-07-22 14:08
@tushspeed  I applied manually the described solution on the file ~/crmint/backends/core/workers.py using the GCloud console and then I run the command `crmint cloud deploy` .

**Comment by Slony** [comment] 2019-07-23 14:48
@bsq-panagiotis thank you for raising this issue, providing a comprehensive context, and giving useful hints on how to fix it.

@dimitris-bsq thank you for applying the suggested solution and confirming that it works.

@ben and @tushspeed thank you for reporting the issue and handling the conversation in this thread.

The issue is fixed with this pull request: [Set a new service name for the GA Reporting API](https://github.com/google/crmint/pull/124).

Please, follow this guide to update your CRMint instance form `dev` branch: [Update CRMint from the dev branch](https://github.com/google/crmint/wiki/Update-CRMint-from-the-dev-branch) and let me know if it works.

Thanks a million!

**Comment by benpowis** [comment] 2019-07-24 10:30
@Slony confirmed working after update, thank you!

**Comment by tushspeed** [comment] 2019-07-25 07:58
@Slony pipeline back to normal after update. Thanks!

**Comment by johanvdwerken** [comment] 2019-07-25 09:39
> @Slony confirmed working after update, thank you!

+1

**Closed** 2019-11-15 11:46 UTC
